<<<<<<< HEAD
title: Rohegg
email: rohegg.art@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rohegg # add your name
author-pic: rohegg.jpg
about-author: íŒí™”ë¥¼ ì „ê³µí•˜ê³  ë§ˆì¼€íŒ…ì„ í•˜ê³  ìžˆìŠµë‹ˆë‹¤. ì±…ì½ê¸°ì™€ ë¬´ì–¸ê°€ì— ëŒ€í•´ ê°ìƒì„ ë‚¨ê¸°ëŠ” ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤. ì´ ê³³ì—ì„œ ìž‘ê²Œë‚˜ë§ˆ ì €ì˜ ìƒê°ì„ í•„í„°ë§ì—†ì´ ê¸°ìž¬í•˜ê³  ìžˆìŠµë‹ˆë‹¤.

# Contact links
email: rohegg.art@gmail.com # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: rohegg # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: rohegg # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: UA-110154972-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
=======
# Blog settings
permalink: /blog/:title


# My variables
name: Rohegg
description: ðŸ³
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]
>>>>>>> parent of e4f8841... ë¸”ë¡œê·¸ í…Œë§ˆ ë³€ê²½


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
